### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by TritiatedWater** [ianmiell/bash2py#2]
Hi
I tried your program and it gives me this error:
`segfault at e ip 000000000042fd72 sp 00007fffc06b7a90 error 4 in bash2pyengine[400000+110000]`
I'm running Linux Mint and Arch Linux, both give me this error.

**Comment by ianmiell** [comment]
Another report:

```
It was just my bash script that somehow did not work, I deleted that part, and now it successfully translated the rest of the script :)
if  [ -z "$GISBASE" ] ; then
 echo "You must be in GRASS GIS to run this program." >&2
 exit 1
fi
```

**Comment by TritiatedWater** [comment]
Just relize this is an upstream issue.
